### ISSUE TITLE
Performance benchmarks

### ISSUE THREAD

**Issue by dumblob** [Thommyy08/sorting#1]
Any performance benchmarks (time + memory usage)? It might be interesting as patience sort seems to have some potential for optimization.

**Comment by ThomasHagebols** [comment]
Thank you for your interest. You might be able to reuse some code snippits in this repo. However, I wouldn't recommend to use this for anything other than toy projects.

This project was the first experience using C++ for me, @DylanRijnen and @markvroling. I wouldn't describe our first C++ attempt as high performance. We sure came a long way since then :sweat_smile:

## Benchmarks

![image](https://user-images.githubusercontent.com/19171292/122582963-0a652680-d059-11eb-996a-e94dd612bdf5.png)

![image](https://user-images.githubusercontent.com/19171292/122583618-be66b180-d059-11eb-956f-d9fa0fc273f4.png)

**Comment by dumblob** [comment]
Thanks. Interesting plots. Will you add them to the readme?

**Comment by ThomasHagebols** [comment]
Updated the readme 😄
